# NodeJS Version 16
FROM satantime/puppeteer-node:20.9.0-buster-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Step 3: Copy package.json and package-lock.json (or yarn.lock) to the container
COPY package*.json ./

# Step 4: Install dependencies inside the container
RUN npm install

# Step 5: Copy the entire project folder into the container
COPY . .

# Step 6: Expose the port the app will run on
EXPOSE 3002

# Cmd script
CMD ["npm", "run", "dev"]
