# NodeJS Version 16
FROM satantime/puppeteer-node:20.9.0-buster-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV development

EXPOSE 3002

# Cmd script
CMD ["npm", "run", "dev"]
